= Development Instructions
Paulo Jerônimo <paulojeronimo@gmail.com>, {localdatetime}
:toc:
:sectanchors:
:sectlinks:
:source-highlighter: highlight.js
:basedir: .
:distdir: .
include::uris/attributes.adoc[]
include::includes/attributes.adoc[]
include::includes/files.adoc[]

This doc gives you some instructions about how to develop this project including some link:#git-commits[history of commands you can use to build this project from scratch].

== Prerequisites

[#git-commits]
== Git commits

=== Fixed deploy to GitHub Pages using environment variables

[#c632]
=== c632: Configured to deploy on GitHub Pages

link:{commits-uri}/c632[See the commit^]

Instruction to deploy the documents:

[source,bash]
----
yarn deploy
----

New instruction to build the documents:

[source,bash]
----
yarn build-docs
----

Created {index_adoc}.

Edited {_gitignore}, {package_json}, {README_adoc} and {DEVELOPMENT_adoc}.

Added {gh-pages} dependency:

[source,bash]
----
yarn add --dev gh-pages
----

[#0936]
=== 0936: Added DEVELOPMENT.adoc and the code to build the asciidoc documents

link:{commits-uri}/0936[See the commit^]

Added {asciidoctor-js} dependencies:

[source,bash]
----
yarn add --dev @asciidoctor/core @asciidoctor/cli highlight.js
git add package.json
----

Edited `scripts` session in {package_json}:

[source,bash]
----
mkdir -p diffs
git diff package.json > diffs/package.json.01.diff
----

[source,diff]
.diffs/package.json.01.diff:
----
include::diffs/package.json.01.diff[]
----

Edited {README_adoc}:

[source,bash]
----
git diff README.adoc > diffs/README.adoc.01.diff
----

[source,diff]
.diffs/README.adoc.01.diff
----
include::diffs/README.adoc.01.diff[]
----

Created the directory `uris` and the file {uris_attributes_adoc} with the following contents:

[source,asciidoc]
----
include::uris/attributes.adoc[]
----

Edited {_gitignore}.

----
git diff .gitignore > diffs/.gitignore.01.diff
----

[source,diff]
.diffs/.gitignore.01.diff
----
include::diffs/.gitignore.01.diff[]
----

Created the file {DEVELOPMENT_adoc} (this file).

Tested the generation of docs (`README.html` and `DEVELOPMENT.html`) with the following command:

----
yarn run build-docs
----

Commited the changes:

[source,diff]
----
git add -A
git commit -m 'Added DEVELOPMENT.adoc and the code to build the asciidoc documents'
----

[#2f14]
=== 2f14: Initial commit

link:{commits-uri}/2f14[See the commit^]

Created {package_json}:

[source,bash]
----
yarn init -y
----

Created {_gitignore}:

[source,bash]
----
echo -e "README.html\nnode_modules" > .gitignore
----

Created the git repo and did the first commit:

[source,bash]
----
git init
git add -A
git commit -y "Initial commit"
git remote add origin git@github.com:paulojeronimo/desafio-82zy.git
git push -u origin master
----
